title: elegant man
author: Gbenromikel
email: your-email@domain.com
theme: minima
description: > # this means to ignore newlines until "baseurl:"
  There is absolutely therefore no condemnation for those in Christ Jesus.

# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  your-github-handle # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
